use_frameworks!

platform :ios, '8.0'

target 'CLRouter_Example' do
  pod 'CLRouter', :path => '../'

  target 'CLRouter_Tests' do
    inherit! :search_paths

#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
  end
end
